allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
patchedDependencies:
  vite-plugin-pwa: patches/vite-plugin-pwa.patch
