packages:
  - 'apps/*'
  - 'packages/*'

nodeLinker: hoisted
autoInstallPeers: true

allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  bcrypt: true
  electron: true
  esbuild: false
  prisma: true
  protobufjs: true
  sharp: false
  vue-demi: true